// Copyright(c) 2020 Ken Okabe
// This software is released under the MIT License, see LICENSEk
#ifndef V1_PHTTP_STATUS_CODE_H_
#define V1_PHTTP_STATUS_CODE_H_

typedef enum {
  kStatusContinue = 100,
  kStatusSwitchingProtocols = 101,
  kStatusProcessing = 102,
  kStatusEarlyHints = 103,

  kStatusOK = 200,
  kStatusCreated = 201,
  kStatusAccepted = 202,
  kStatusNonAuthoritativeInfo = 203,
  kStatusNoContent = 204,
  kStatusResetContent = 205,
  kStatusPartialContent = 206,
  kStatusMultiStatus = 207,
  kStatusAlreadyReported = 208,
  kStatusIMUsed = 226,

  kStatusMultipleChoices = 300,
  kStatusMovedPermanently = 301,
  kStatusFound = 302,
  kStatusSeeOther = 303,
  kStatusNotModified = 304,
  kStatusUseProxy = 305,
  kStatusTemporaryRedirect = 307,
  kStatusPermanentRedirect = 308,

  kStatusBadRequest = 400,
  kStatusUnauthorized = 401,
  kStatusPaymentRequired = 402,
  kStatusForbidden = 403,
  kStatusNotFound = 404,
  kStatusMethodNotAllowed = 405,
  kStatusNotAcceptable = 406,
  kStatusProxyAuthRequired = 407,
  kStatusRequestTimeout = 408,
  kStatusConflict = 409,
  kStatusGone = 410,
  kStatusLengthRequired = 411,
  kStatusPreconditionFailed = 412,
  kStatusRequestEntityTooLarge = 413,
  kStatusRequestURITooLong = 414,
  kStatusUnsupportedMediaType = 415,
  kStatusRequestedRangeNotSatisfiable = 416,
  kStatusExpectationFailed = 417,
  kStatusTeapot = 418,
  kStatusMisdirectedRequest = 421,
  kStatusUnprocessableEntity = 422,
  kStatusLocked = 423,
  kStatusFailedDependency = 424,
  kStatusTooEarly = 425,
  kStatusUpgradeRequired = 426,
  kStatusPreconditionRequired = 428,
  kStatusTooManyRequests = 429,
  kStatusRequestHeaderFieldsTooLarge = 431,
  kStatusUnavailableForLegalReasons = 451,

  kStatusInternalServerError = 500,
  kStatusNotImplemented = 501,
  kStatusBadGateway = 502,
  kStatusServiceUnavailable = 503,
  kStatusGatewayTimeout = 504,
  kStatusHTTPVersionNotSupported = 505,
  kStatusVariantAlsoNegotiates = 506,
  kStatusInsufficientStorage = 507,
  kStatusLoopDetected = 508,
  kStatusNotExtended = 510,
  kStatusNetworkAuthenticationRequired = 511,
} PhttpStatusCodes;

#endif  // V1_PHTTP_STATUS_CODE_H_
